repos:
  - repo: local
    hooks:
      - id: format-python
        name: Format with Ruff
        entry: uv run ruff format .
        language: system
        pass_filenames: false

      - id: update-toc
        name: Update README TOC
        entry: uv run markdown-toc README.md
        language: system
        pass_filenames: false
