[project]
name = "uv-sandbox"
version = "0.1.0"
description = "For CUDA 11.8 environments"
readme = "README.md"
requires-python = ">=3.9"

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"

[dependency-groups]

gpu = ["torch>=2.6.0"]
common = ["ruff>=0.11.2"]
